CREATE DATABASE ShopPC_data
GO
USE ShopPC_data;
GO
CREATE TABLE TheLoai (
    MaTL INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TenTL VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    MoTaTL TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
)
GO

CREATE TABLE SanPham(
	MaSP INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	TenSP VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
	MaTL INT,
	DonGiaSP FLOAT,
	TonKhoSP SMALLINT,
	Chip VARCHAR(50),
	Main VARCHAR(100),
	VGA VARCHAR(50),
	NhanSanXuat VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
	RAM VARCHAR(100),
	AnhSP TEXT
)
GO

CREATE TABLE NhanVien(
	MaNV VARCHAR(255) NOT NULL PRIMARY KEY,
	PassNV VARCHAR(255),
	HoLotNV VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
	TenNV VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
	DiaChiNV VARCHAR(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
	SdtNV VARCHAR(24),
	AnhNV TEXT,
	GhiChu TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
)
GO

CREATE TABLE KhachHang(
	MaKH VARCHAR(255) NOT NULL PRIMARY KEY,
	PassKH VARCHAR(255),
	TenLienHe VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
	DiaChi VARCHAR(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
	Sdt VARCHAR(24)
)
GO

CREATE TABLE HoaDon(
	MaHD INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	MaKH VARCHAR(255),
	MaNV VARCHAR(255),
	DiaChiShip VARCHAR(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
)
GO

CREATE TABLE ChiTietHoaDon(
	MaHD INT,
	MaSP INT,
	SoLuong SMALLINT,
	GiamGia FLOAT,
	PRIMARY KEY (MaHD, MaSP)
)